name: PMD Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pmd-analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write #pour les alertes de securités

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run PMD
        id: pmd
        uses: pmd/pmd-github-action@v2
        with:
          rulesets: 'category/java/errorprone.xml' 
          sourcePath: 'app/src/main/java'
          analyzeModifiedFilesOnly: false
          failOnViolation: true 

      - name: Upload PMD Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pmd-report
          path: pmd-report.sarif
